name: bayespecon
channels:
  - conda-forge
dependencies:
  - libpysal
  - formulaic
  - pymc
  - arviz
  - spreg
  - statsmodels
  - geopandas
  - geodatasets
  - arviz < 1  #pinned until supported by pymc
  - lazy_loader
